### ISSUE TITLE
[OSX] Error: ENOTDIR: not a directory... .DS_Store

### ISSUE THREAD

**Issue by CandyFace** [superpowers/superpowers#10]
Whenever i'm trying to start the server, it crashes immediately, trying to locate the templates.json file in .DS_Store before looking into the supGame folder. You can start the server if you remove the file, but you'll have to do it every time you want to start it.

App threw an error when running { [Error: ENOTDIR: not a directory, open '../superpowers-master/systems/.DS_Store/public/templates.json']
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'open',
  path: '../superpowers-master/systems/.DS_Store/public/templates.json' }

**Comment by elisee** [comment]
Thanks for the report, fixed for v0.18!

**Comment by CandyFace** [comment]
i just tried with latest commit and now i'm getting.. Error: ENOTDIR: not a directory, scandir '../superpowers/systems/supGame/plugins/.DS_Store'

**Comment by CandyFace** [comment]
@bilou84 
i tried again with your commits, though it is back to Error: ENOTDIR: not a directory, open '../superpowers/systems/.DS_Store/public/templates.json'

**Comment by bilou84** [comment]
Sorry about that, I accidentaly removed the previous fix with the new one... (not really used to git just yet)

**Comment by CandyFace** [comment]
Git can be confusing at times... though thanks! it works now :)

**Comment by bilou84** [comment]
Great :)
