### ISSUE TITLE
launcher: Translation for "Cancel" is missing

### ISSUE THREAD

**Issue by Peekmo** [superpowers/superpowers#12]
Hello,

I just downloaded your first release for linux 64, and there's a problem for the translation of the "cancel" button when I click on "Add Server" (see screenshot)

![Screenshot of error](http://i.imgur.com/hGKE2B4.png)

I looked into "locales" in your repo, there's the translation. So, it's strange^^

Regards,
Peekmo

**Comment by bilou84** [comment]
Hello!
Yeah we already know this bug. The launcher doesn't support internalization so this is kind of a side effect of our architecture...
We will entirely redesign the launcher pretty soon so we didn't really bother fixing it '^^

**Comment by elisee** [comment]
Closing since this is fixed in `master` now that dialogs have a default label if no internationalization support is present. And the new launcher will be translatable so it won't be an issue.
