### ISSUE TITLE
new ImageData error chromium

### ISSUE THREAD

**Issue by DavidMeagher1** [superpowers/superpowers#13]
runtime.js:1394 Uncaught TypeError: Failed to construct 'ImageData': Illegal constructor

var imageData = new ImageData(new Uint8ClampedArray(map), data.textureWidth, data.textureHeight);

I am using node-webkit to run a simple test game, after publishing it it won't run. seems to work fine in the editor though i haven't taken a look. but i thought i would put this here for now

**Comment by abclive** [comment]
Did you follow this documentation to export/publish your game ?

http://docs.superpowers-html5.com/en/getting-started/publishing-your-game

**Comment by elisee** [comment]
Which version of node-webkit / NW.js are you running? I believe you might just need a more recent version of Chromium. As @abclive pointed out, the documentation recommends using Electron which is updated more often than NW.js and known to work.

**Comment by DavidMeagher1** [comment]
i did not read the docs for that, thank you this was very helpful thank you :)
