### ISSUE TITLE
[DOCS] Mention that you cannot use setLocalPosition or setPosition if there is an ArcadeBody2D.Body attached to the Actor

### ISSUE THREAD

**Issue by nounoursheureux** [superpowers/superpowers#33]
I didn't find the docs source code, so I figured I would just create an issue here.
I think you should mention that when an `ArcadeBody2D.Body` is attached to an Actor you cannot use `setPosition` or `setLocalPosition` on this Actor. Of course it makes sense, but I just spent half an hour debugging my code and it wasn't obvious at all :P 
I know you are all really busy, so if the docs are available just tell me where they are and I will make the modification myself :+1:

**Comment by nounoursheureux** [comment]
The docs are here: https://bitbucket.org/superpowers/docs.sparklinlabs.com/

**Comment by bilou84** [comment]
This information is written here.
http://docs.superpowers-html5.com/en/tutorials/collision-2d
Maybe not super obvious, but it exists ^^

**Comment by nounoursheureux** [comment]
Okay it's completely my fault. Sorry about that... :/
