### ISSUE TITLE
Cut-Copy-Paste key bindings not working on Mac OSX

### ISSUE THREAD

**Issue by rjrodger** [superpowers/superpowers#37]
Following http://docs.superpowers-html5.com/en/getting-started/first-game

The editor does not support Command-X,C,V consistently.

Right-click menu does work.

**Comment by elisee** [comment]
Thanks for the report! There's already an issue for it here: superpowers/superpowers-common-plugins#3 but let's keep this one open too since people are unlikely to look through all repositories to find it.

We should be able to fix this for the next release!

**Comment by rjrodger** [comment]
I'd rate this as very very very high priority - it's pretty much "game over" if the editor doesn't work :)

**Comment by rjrodger** [comment]
:+1: :smile:
