### ISSUE TITLE
Add an URL which always serves the last build of the project

### ISSUE THREAD

**Issue by bilou84** [superpowers/superpowers#39]
The URL should probably be something like `?build=latest` instead of current `?build=buildId`.

At least this particular section need modification.
https://github.com/superpowers/superpowers/blob/9fcff9f0bad576729f22fbd3c8c1aa56a721d04c/server/index.ts#L121

**Comment by Pangoraw** [comment]
Hi, I worked on that and I came up with [this](https://github.com/superpowers/superpowers/pull/40).
