### ISSUE TITLE
Documentation is blank

### ISSUE THREAD

**Issue by Deozaan** [superpowers/superpowers#41]
I'm not sure if the Documentation window is where I'm supposed to write documentation for my project or if it's supposed to be documentation on how to use Superpowers, but either way something about it is broken.

I just see a blank window with a grey sidebar. I can't edit or change anything there, so right now it's pretty useless.

![superpowers documentation](https://cloud.githubusercontent.com/assets/227734/12279173/ed5ff4c6-b942-11e5-834a-471c4a77b551.png)

**Comment by bilou84** [comment]
This is a known bug and it will be fixed for the next release (pretty soon).
It is supposed to be the documentation for Superpowers ^^

**Comment by elisee** [comment]
In the meantime, most of the documentation can be found here: http://docs.superpowers-html5.com/
