### ISSUE TITLE
client: Duplicating a project entry with a Draft badge throws error

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#42]
Maybe the badge update is sent before the entry itself?

    Uncaught TypeError: Cannot read property 'byId' of undefined
    onBadgeSet @ index.js:393
    Emitter.emit @ SupClient.js:1569Socket.onevent

**Comment by florentpoujol** [comment]
Sidenote #1 : should all errors in the console be treated as bugs that should be fixed even when they aren't blocking at all ?

Sidenote #2 : when building the server tslint complain about instalPlugin() not been used

**Comment by elisee** [comment]
> @florentpoujol: Sidenote 1 : should all errors in the console be treated as bugs that should be fixed even when they aren't blocking at all ?

I would say yes. It indicates either a design or implementation error. We should strive to avoid them at all.

> Sidenote 2 : when building the server tslint complain about instalPlugin() not been used

I believe @bilou84 is still working on plugin installation so it is currently disabled?
