### ISSUE TITLE
Logging in to server with invalid(?) username gives no error

### ISSUE THREAD

**Issue by d-Pixie** [superpowers/superpowers#44]
When starting a server and double clicking to open it you are presented with a screen where you type your username. I typed `d-Pixie`, as usual, and saw something flicker when I pressed enter just to find myself back at the same screen.

After a while I tried without the hyphen and that worked. But I would expect an invalid username to give a message to that effect so I knew what to fix :)

I'm on OS X El Capitan running v0.18.1

**Comment by rhin0cer0s** [comment]
After wandering for a while inside the sources I found this in ```server/authenticate.js``` : 
```let usernameRegex = /^[A-Za-z0-9_]{3,20}$/; ```

It seems that since the username is not meant to authenticate and just gives an ID - for the chat I presume - they decided to put some restriction on it.

The regex accepts no special characters other than ```_```.

**Comment by d-Pixie** [comment]
Yeah, and that is perfectly fine :) But the GUI should tell the user, how else will the user know what went wrong?

**Comment by elisee** [comment]
Agreed, there should be an error message here.

We can do this client-side by simply adding `pattern="[A-Za-z0-9_]{3,20}"` validation in [client/src/login/index.jade](https://github.com/superpowers/superpowers/blob/aabc5d62671d229bea58a8cb8834fd093c0c59df/client/src/login/index.jade#L29). Anyone up to submit a pull request?

**Comment by rhin0cer0s** [comment]
I'll give it a try.

**Comment by elisee** [comment]
Just remembered that [Electron doesn't support HTML5 validation bubbles](https://github.com/atom/electron/issues/1043) at the moment so this will have to be tested in the browser for now. I don't know if we can / should look for a polyfill or just accept that it won't display anything for now?

Also, now that I think about it, we should totally allow dashes in usernames, shouldn't we? Feel free to submit a Pull Request that updates the pattern to include the dash.

**Comment by rhin0cer0s** [comment]
There has to be an error or it is difficult to understand what's wrong. Adding a little sentence under the form might be the best solution here.

About the regex I don't know why you restricted it in the first place. Could the full utf-8 set create some hassle ?

**Comment by elisee** [comment]
OK this should do the trick:

 * d833950ada2fa78b4389648e027d7f71ad0245b5: Add client-side with localized title
 * 2334cabe86790d0d4f49413ed487b1f430659bec: Put a redish outline around invalid fields

The title means the instructions will appear when hovering the username field, along with the red outline, I think this is good enough for now. And it'll be better when Electron implements HTML5 validation bubbles.
