### ISSUE TITLE
See if we can be promoted on Nintendo Wii U dev portal

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#45]
Quoting https://twitter.com/paprikorange/status/687225738026729472:

> @SuperpowersDev do you already have contact to Nintendo? They could promote you on https://wiiu-developers.nintendo.com/  like Construct 2 & Co

**Comment by Paprikorange** [comment]
The first thing you'll probably want to do is register for a WiiU developer account here: https://wiiu-developers.nintendo.com/signup/ 

As someone who is a registered developer with Nintendo, Microsoft and Sony I can assure you this is the most painless of the three. When asked "Which types of applications are you interested in developing?" I'd not only hit "Games" but also "Other" and then introduce Superpowers.

Once Nintendo approves your account, you'll have access to the official WiiU developer forums as well as the developer portal where you're not only getting access to the Nintendo Web Framework but also to the ordering page for devkits. When you're that far, getting the attention of a Nintendo official should be rather easy. They may even provide you a devkit free of charge (?) so you can make sure Nintendo Web Framework runs well with Superpowers games. Pretty sure they will then have no problem featuring you on their developer front page ☺

**Comment by bigelod** [comment]
So far the WiiU doesn't support WebGL which might be troublesome, and reports from some Construct 2 users is that real-time games are generally unplayable on it. (especially if there are any physics or complex actions going on in the game)

But if it ever gets WebGL it would be cool to see how close performance is to that of the Edge browser on Xbox One.

**Comment by elisee** [comment]
If there's no WebGL support then it's basically game over ^_^, at least for the Superpowers Game system. Maybe once we have a good Phaser.js system or something like that.

Closing for now, feel free to dig it up if there's new development.
