### ISSUE TITLE
Upgrade to Socket.IO 1.4

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#48]
Socket.IO 1.4 no longer has a hard dependency on the native `bufferutil` module which is nice as it will remove many spurious errors from the build for people who don't have Python + a C++ compiler installed. Also it has cool [new features / better perf](http://socket.io/blog/socket-io-1-4-0/).

 * [x] Update `package.json` to reference `~1.4.4`
 * [x] Figure out how the internal `adapter.rooms` API changed and [update RemoteProjectClient.ts](https://github.com/superpowers/superpowers/blob/master/server/RemoteProjectClient.ts#L211) consequently
 * [x] Update Socket.IO-client to 1.4 [in the socketio plugin](https://github.com/superpowers/superpowers-game/tree/master/plugins/extra/socketio) of Superpowers Game

**Comment by florentpoujol** [comment]
I will try to do that this week-end.
I am not sure about the `adapter.rooms` but I will learn.

The current definition for socket.io and the socket.io-client on DefinitelyTyped have comments.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffceea9dd124d277c4597c7bd12930666ec074c5/socket.io/socket.io.d.ts
Do you want me to keep them in the definitions for Superpowers ?

**Comment by elisee** [comment]
Cool.

> @florentpoujol: Do you want me to keep them in the definitions for Superpowers ?

Yeah, best is to update the definition using `tsd` since that what we've been using to install them in the first place
