### ISSUE TITLE
Identification security considerations

### ISSUE THREAD

**Issue by rhin0cer0s** [superpowers/superpowers#52]
I spend some time around ```server/authenticate.ts``` and have some considerations regarding the way it is handled.

Firstly the password must be stored hashed. If the server is ever taken over from another way it shall not give this indication easily.

Secondly the use of a stronger way to compare credentials is a must have. Currently a brute-force attack would be easily executed. Something like [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) is a great first step. A credentials validation has to be *slow*.

Thirdly I looked over some network exchanges - just from the web developers tool in iceweasel - and I saw a lot of GET request containing ```{password, login}```. This duple seems to be stored in a cookie ... in plain text. That's a big no no. Is the identification taking place at every exchange ? If so, it should not.

I am not used to nodeJS nor websocket so I need some time before going further but these behaviors are dangerous.
Obviously this is nearly useless without https, but this point needs it own issue.

**Comment by elisee** [comment]
Right! The clear text global server password was just a stop-gap way to make one's server available without letting everyone fiddle with your projects... but now that Superpowers is getting some attention, we should definitely deal with it sooner rather than later! Thanks for raising this issue. Let's try and get this done for the next release.

**Comment by elisee** [comment]
Somewhat related: http://itch.io/t/13677/identity-user-settings-and-project-membership

**Comment by elisee** [comment]
Closing this in favor of #55, please share feedback over there =)
