### ISSUE TITLE
fr: "Upload" should not be translated as "Télécharger"

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#54]
[`fr/common.json`](https://github.com/superpowers/superpowers/blob/d2e452e2113065a1be8c704f5d980b2fa54b2f81/public/locales/fr/common.json#L23) as contributed by @Pangoraw translates "Upload" as "Télécharger". We often use "Download" and "Upload" together, so it leads to confusion:

![](http://screens.anatagawa.fr/test_2_%E2%80%94_Superpowers_2016-01-14_19-23-34.png)

We might want to use "Téléverser", although from a quick strawpoll I did a while ago, there are still lots of people who have never heard the word.

cc @cosmikats @Pangoraw

**Comment by rhin0cer0s** [comment]
"charger" or "envoyer" could do the trick too.

**Comment by elisee** [comment]
We did this pull request as a demo during the stream. The consensus seemed to be that "Téléverser" is too obscure, so we went with "Uploader" for now. I'm not very happy with it, but I don't feel that "Charger" or "Envoyer" are very clear either.
