### ISSUE TITLE
Removing File when Open

### ISSUE THREAD

**Issue by lagonnebula** [superpowers/superpowers#6]
I just find a bug, in the master version and in the 0.17 version.
If you try to delete a file when you have it opened the server crash with this error : 
````Javascript
2016-01-06 22:11:06 - The server crashed.
TypeError: Cannot read property 'socket' of undefined
    at superpowers\server\RemoteProjectClient.js:198:49
    at Entries.TreeById.remove (superpowers\SupCore\Data\Base\TreeById.js:165:9)
    at Entries.remove (superpowers\SupCore\Data\Entries.js:85:33)
    at superpowers\server\RemoteProjectClient.js:185:55
    at superpowers\node_modules\async\lib\async.js:718:13
    at Immediate.iterate [as _onImmediate] (superpowers\node_modules\async\lib\async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

````

**Comment by elisee** [comment]
Looks like socket.io@1.4.0 was released 22 hours ago and breaks our usage of the undocumented `io.adapter.rooms` API.

I've just locked down the semver range for it in `package.json` to 1.3.x. Can you try pulling and doing a `npm install` at the root and see if that fixes it?

**Comment by lagonnebula** [comment]
It's work perfectly. Thanks

**Comment by elisee** [comment]
Good to know! We'll look into what exactly changed in socket.io@1.4 soon, but in the meantime, you saved tomorrow's release from a very bad bug, so thank you!
