### ISSUE TITLE
font: Can't zoom in/out with plus/minus in the Font editor

### ISSUE THREAD

**Issue by ArgosOz** [superpowers/superpowers#65]
Mac, Yosemite, 10.10.4

So there's no other option to workaround "Uncontrollably Fast Zoom In and Out" issue for Magic Trackpad users:
https://github.com/superpowers/superpowers/issues/62

**Comment by elisee** [comment]
Thanks for the report! Fixed for the version in https://github.com/superpowers/superpowers-game/commit/d605ea95fcd531d3dd6dfa74da999965a972526b
