### ISSUE TITLE
client: Add an asset type filter to the project tree

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#71]
There should be a funnel button next to the search button that toggles a panel (below the asset management buttons but above the asset tree) with an icon for every asset type.

 * Clicking on one of them filters the whole tree to display only that type of asset
 * Right-clicking on one of them would enable/disable it (multiples can be active at once)
 * There would be a "reset" button as the first icon that enables all the icons

**Comment by chrisbubernak** [comment]
I know this issue isn't marked as "help wanted" but if you haven't started on something can I take a look at this? I started briefly working on it to get familiar with the codebase and think I can get something working but If you'd rather work on it I'll just go look into one of the other open issues.

**Comment by elisee** [comment]
@chrisbubernak sure, go for it! :)
