### ISSUE TITLE
mixing javascript with typescript? 

### ISSUE THREAD

**Issue by Elmapul** [superpowers/superpowers#80]
its not really an issue, more like an "help" (im sorry if this isnt the right place for it) 
i want re use my own project code on super powers but its in javascript, and i didn't figure out how to mix javascript with TS, acording to microsoft any javascript code should be an valid typescript code, but when i try an simple alert or console.log test i got errors, even microsoft typescript "helloworld" don't work.

im not sure but i guess the syntax highlight and compiler is only checking for typescript code instead of acept both js and js?

i can port my own code to typescript, but thirdyparty libraries that im using would be  PITS

**Comment by elisee** [comment]
The best place to ask for help are [the itch.io community forums](http://itch.io/engine/superpowers/community), but here is fine too.

The reason your code doesn't work is that we don't expose all the DOM APIs by default in Superpowers Game. See [this page for an explanation and solution](http://docs.superpowers-html5.com/en/tutorials/dom-apis).

**Comment by florentpoujol** [comment]
The link to my plugin in the doc is wrong : it's now
https://github.com/florentpoujol/superpowers-game-dom-plugin

**Comment by Elmapul** [comment]
"The best place to ask for help are the itch.io community forums, but here is fine too."
thanks i will ask here, since i already have too many accounts on the internet  (therefore to many passwords to remember or manage and its anoying register everywhere, sugestion: acept open-id as sign in)

"See this page for an explanation and solution."
thanks
