### ISSUE TITLE
Electron problem: Drag'n'drop Web page.

### ISSUE THREAD

**Issue by NattackDev** [superpowers/superpowers#84]
### Hi ! 
I found a **problem** when I **drag and drop** a website adress into the **electron application** of Superpowers. 
The application loads the link but you cannot go back and any of the links in the **electron app** don't run in some cases.

##### Nattack

**Comment by elisee** [comment]
Thanks for the report. Fixed in bfbc2e23375862406074c21e8a6c1f9f5311eceb
