### ISSUE TITLE
Docs: Stuck at username question

### ISSUE THREAD

**Issue by DarrenCook** [superpowers/superpowers#85]
It feels like something is missing on http://docs.superpowers-html5.com/en/getting-started/setting-up-superpowers

I downloaded the 64-bit linux version, unzipped, and then I double-clicked the "Superpowers" executable.
The splash screen appears, I click to remove it.
I see "My Server 127.0.0.1:4237".
Double-clicking it, it asks for username. At this point the docs say: " You'll be asked to choose a username. This is not yet linked to your Superpowers account but you probably want to use the same."

So I tried some random username, but it just stays on that screen. There are no usernames listed in ~/.local/share/Superpowers/config.json   (just two ports, a blank password (which is for other people to login to your server, I assume), and `maxRecentBuilds:10`)

Aha, while typing this issue, I tried "guest" and that worked!

So: the docs need to say something like:
   Give "guest" as the username, when prompted. To add your own users [...link to instructions here...].

I think you also need to say that the server Superpowers window need to be kept open all the time.

**Comment by elisee** [comment]
Hi @DarrenCook and thanks for the report!

There's nothing special about "guest", any username should do the trick. Just make sure it's at least 3 characters long and only includes letters, digits, dashes or underscores. We've improved the feedback for errors in this form for the next version, see #44.

We definitely need to update the wiki page though as it mentions a Superpowers global account but there won't be any :) see #55.
