### ISSUE TITLE
SupClient.projectClient.editAsset/Resource should handle errors

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers#86]
Rather than duplicating:

    if (err != null) {
      new SupClient.dialogs.InfoDialog(err, SupClient.i18n.t("common:actions.close"));
      return;
    }

in our edit asset callbacks everywhere, `SupClient.projectClient.editAsset` and `.editResource` should do it by default (and we can always provide an alternative version that doesn't, if needed).

See also: https://github.com/superpowers/superpowers-game/issues/41

**Comment by bilou84** [comment]
Done here. https://github.com/superpowers/superpowers/commit/c0e825aeb2b819dcb55be67cf8e8bc16c90983d1
