### ISSUE TITLE
Error when lauching on Raspberry Pi

### ISSUE THREAD

**Issue by wdhif** [superpowers/superpowers#89]
Hi sparklinlabs guys,

Awesome job you did with superpowers!

I'm trying to launch superpowers as a server on a Raspberry Pi, but I get the following error :
`Cannot GET /index.view`

Yet the server logs looks normal to me: 
`node server start`
`2016-01-28 10:41:19 - Using data from /home/wassim/.local/share/Superpowers.`
`2016-01-28 10:41:19 - Server v0.19.0 starting...`
`2016-01-28 10:41:19 - Using data from /home/wassim/.local/share/Superpowers.`
`2016-01-28 10:41:19 - Server v0.19.0 starting...`
`2016-01-28 10:41:27 - Loaded 0 projects from /home/wassim/.local/share/Superpowers/projects.`
`2016-01-28 10:41:27 - Main server started on port 4237, build server started on port 4238.`
`^C`
`2016-01-28 10:43:42 - Saving all projects...`
`2016-01-28 10:43:42 - Exited cleanly.`

I also get a 404 error in my browser console `Failed to load resource: the server responded with a status of 404 (Not Found)`

I'm using `node v4.2.6` with Raspbian and superpowers-0.19.0-linux-ia32

If you want to see for yourself, I'll let the server run, you can access it with [here](http://www.wassimdhif.tk) with this password : superpowers

Best regards,
Wassim Dhif

**Comment by wdhif** [comment]
Actually I can connect to the server using the Superpower client. But the server should not be accessible from a browser ?

**Comment by elisee** [comment]
Hey! Did you change the password in the meantime? I can't seem to log in. The login page loads fine though.

`Cannot GET /index.view` sounds weird, I'm not sure where `.view` is coming from.

**Comment by wdhif** [comment]
Yes, you can see here the config.json:
`{`
`  "mainPort": 4237,`
`  "buildPort": 4238,`
`  "password": "superpowers",`
`  "maxRecentBuilds": 10`
`}`

I don't know either for the .view, it's pretty strange, I'll try on a different machine.

**Comment by wdhif** [comment]
Ok so, I got an update,

I changed the domain name to http://www.wassimdhif.fr/, and now I can access the login page. so I think it's just a caching problem.

But I now get the same issue as you do, I can't login, but the password is correct, I get an error in my browser console, `GET http://www.wassimdhif.fr/locales/fr/login.json 404 (Not Found)`

**Comment by elisee** [comment]
The error about `login.json` is because the French localization isn't complete yet so nothing to worry about.

So I dug a bit and the credentials are correctly collected from the cookie and sent through socket.io but the server returns `"invalidCredentials"` and that's why we're being redirected to the login page.

That's just plain strange. Maybe you can add some `console.log()` calls in `server/authenticate.js` to check what values are being passed to the socket.io server and which conditions fail.

**Comment by wdhif** [comment]
I tried to change the password to `test` and now I can connect, but it was really strange.

You can try again if you want, but there is still a problem with the building part, should I do port forwarding for the building port (4328) ?

**Comment by wdhif** [comment]
Oh actually I am doing port forwarding for 4328 so never mind.
Still the building doesnt seem to work.

If you want, I can give you an ssh access to the server.

**Comment by elisee** [comment]
Seems like the server just doesn't respond on port 4238 so I would assume it's a firewall or port forwarding issue more than anything else. Maybe double-check the local IP you redirected to?

**Comment by wdhif** [comment]
Yes my bad, I did a port forwarding on 4238. The IP is also correct, I'll keep searching, I think it might be a networking issue.

**Comment by wdhif** [comment]
I can developpe with http://www.wassimdhif.fr:4237/ (and http://www.wassimdhif.fr:80/ with iptables redirect) but when I try to build, I think it's trying to use the 80 port, I also don't get any resources like SupCore.js or SupEngine.js, I only get the building.html

**Comment by elisee** [comment]
http://www.wassimdhif.fr:4238/ didn't seem to reply to connections at all when I tried earlier so I'd think that's the primary issue

**Comment by elisee** [comment]
@wdhif Did you manage to get it working?
