### ISSUE TITLE
Set minimum scale value to 1 

### ISSUE THREAD

**Issue by basiclaser** [superpowers/superpowers#98]
An error occurs if an object's scale is set to 0 in any of the axis. 

`Matrix3.getInverse(): can't invert matrix, determinant is 0`

As an object cannot have a dimension scale of 0 (AFAIK), we should prevent it from being an option.

**Comment by elisee** [comment]
It's perfectly OK to have a scale of 0.01 for instance, but zero scale is not well supported by Three.js indeed. So the scale should be != 0, not >= 1.
